## Load libraries

In [1]:
import os
import numpy as np
from sklearn.metrics import accuracy_score

from alphai_watson.transformer import NullTransformer
from alphai_rickandmorty_oracle.datasource.kddcup99 import KDDCup99DataSource
from alphai_rickandmorty_oracle.detective import RickAndMortyDetective
from alphai_rickandmorty_oracle.model_kddcup99 import RickAndMorty

/opt/anaconda/envs/ai/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/opt/anaconda/envs/ai/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
DEBUG:matplotlib:CACHEDIR=/home/ubuntu/.cache/matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from /home/ubuntu/.cache/matplotlib/fontList.json
DEBUG:matplotlib.backends:backend agg version v2.2


Enabling weight norm
Uppercase local vars:
	BATCH_SIZE: 50
	CRITIC_ITERS: 5
	DEFAULT_FIT_EPOCHS: 1000
	DEFAULT_LEARN_RATE: 0.0001
	DEFAULT_TRAIN_ITERS: 5000
	DEFAULT_Z_DIM: 32
	DIAGNOSIS_LEARN_RATE: 0.01
	DIM: 64
	DISC_FILTER_SIZE: 5
	INIT_KERNEL: <function variance_scaling_initializer.<locals>._initializer at 0x7f99420308c8>
	LAMBDA: 10
	LAMBDA_2: 2.0
	OUTPUT_DIM: 121


## Define KDDCup99 Datasource

In [2]:
file_path = '../../tests/resources'
data_filename = os.path.join(file_path, 'kddcup.data_10_percent_corrected')
header_filename = os.path.join(file_path, 'kddcup.names')

kdd_datasource = KDDCup99DataSource(source_file=data_filename,
                                    header_file=header_filename,
                                    transformer=NullTransformer(8, 8))

DEBUG:root:Start file parsing.
DEBUG:root:Normal (97278, 122); Train (68095, 121); Test(29183, 121)
DEBUG:root:Abnormal (396743, 121)
DEBUG:root:End file parsing.


In [3]:
data_normal_train = kdd_datasource.get_train_data('NORMAL')
data_normal_test = kdd_datasource.get_train_data('NORMAL_TEST')
data_abnormal_test = kdd_datasource.get_train_data('ABNORMAL_TEST')

## Define Model

In [4]:
model_dir = './kddcup99_models'
if not os.path.exists(model_dir):
    os.makedirs(model_dir)

batch_size = 64
output_dimensions = 121
train_iters = 5000
plot_save_path = model_dir


model = RickAndMorty(batch_size=batch_size, 
                     output_dimensions=output_dimensions, 
                     train_iters=train_iters,
                     plot_save_path=plot_save_path)

detective = RickAndMortyDetective(model_configuration={
    'model': model,
    'batch_size': batch_size,
    'output_dimensions': output_dimensions,
    'train_iters': train_iters,
    'save_path' : '{}/KDDCup99-model'.format(model_dir),
    'plot_save_path': plot_save_path
    
})

detective.train(data_normal_train)

DEBUG:root:Starting session
DEBUG:root:Start training loop...
INFO:root:Initialising Model
INFO:root:Training iteration 0 of 5000
DEBUG:matplotlib.font_manager:findfont: Matching :family=sans-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to DejaVu Sans ('/opt/anaconda/envs/ai/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf') with score of 0.050000


iter 0	train disc cost	1.40699303150177	time	0.2448716163635254
iter 1	train disc cost	1.3974802494049072	time	0.09613513946533203
iter 2	train disc cost	1.3884327411651611	time	0.0698392391204834
iter 3	train disc cost	1.381819725036621	time	0.06876945495605469
iter 4	train disc cost	1.3731675148010254	time	0.06925320625305176


INFO:root:Saving fake samples to png: [[0.41805136 0.49184462 0.33828667 ... 0.42984244 0.7013362  0.45790234]
 [0.49009722 0.43069816 0.24066429 ... 0.3707566  0.7203298  0.315169  ]
 [0.33672014 0.34398967 0.14408535 ... 0.45157048 0.894819   0.44627225]
 ...
 [0.30315754 0.55272675 0.33372548 ... 0.40814468 0.57585335 0.33994374]
 [0.3340342  0.4488595  0.34052995 ... 0.28190556 0.6200631  0.20405743]
 [0.52082443 0.45182753 0.31982878 ... 0.49610806 0.7674867  0.2237428 ]]
INFO:root:Training iteration 100 of 5000


iter 99	train disc cost	0.7504642605781555	time	0.06763864567405299


INFO:root:Saving fake samples to png: [[0.26652488 0.3239614  0.16997682 ... 0.2383358  0.8180934  0.29803437]
 [0.27067325 0.22321616 0.07419454 ... 0.15038745 0.87452495 0.14255461]
 [0.12656288 0.14756785 0.02459306 ... 0.21123168 0.97343564 0.20105238]
 ...
 [0.12111598 0.34790075 0.12402461 ... 0.22803043 0.7579735  0.17244723]
 [0.13156505 0.2049903  0.09183554 ... 0.10209616 0.8221306  0.0615277 ]
 [0.3030559  0.2823234  0.11632933 ... 0.2847314  0.90555334 0.08318748]]
INFO:root:Training iteration 200 of 5000


iter 199	train disc cost	0.281014084815979	time	0.0588991904258728


INFO:root:Saving fake samples to png: [[0.09640247 0.13218038 0.04191715 ... 0.08122792 0.9307422  0.10664953]
 [0.06118651 0.05519333 0.01011292 ... 0.03039382 0.9702355  0.02900585]
 [0.01751832 0.02895855 0.00180754 ... 0.04260842 0.9969105  0.03876499]
 ...
 [0.02153135 0.11089271 0.02535958 ... 0.06434204 0.9321072  0.04147818]
 [0.01582818 0.04087077 0.00983686 ... 0.01721171 0.96965796 0.00821098]
 [0.07908115 0.07862447 0.01901308 ... 0.07661591 0.9814736  0.0172968 ]]
INFO:root:Training iteration 300 of 5000


iter 299	train disc cost	0.2791493237018585	time	0.06169396162033081


INFO:root:Saving fake samples to png: [[1.5740192e-02 2.6195299e-02 4.9131652e-03 ... 1.3891394e-02
  9.8546278e-01 2.0084778e-02]
 [5.7585919e-03 6.4446153e-03 6.9100951e-04 ... 3.0368359e-03
  9.9589443e-01 2.8542301e-03]
 [9.1590657e-04 2.4314760e-03 6.4628126e-05 ... 3.2561896e-03
  9.9975210e-01 2.8556758e-03]
 ...
 [2.0483113e-03 1.7657047e-02 2.7149222e-03 ... 8.4482552e-03
  9.8861897e-01 5.0155357e-03]
 [7.4627285e-04 3.0793736e-03 4.2047055e-04 ... 1.2022926e-03
  9.9712950e-01 5.1074871e-04]
 [9.2616286e-03 9.5186764e-03 1.5043161e-03 ... 9.3685966e-03
  9.9765331e-01 2.0822096e-03]]
INFO:root:Training iteration 400 of 5000


iter 399	train disc cost	0.3889649510383606	time	0.061550514698028566


INFO:root:Saving fake samples to png: [[1.5749226e-03 3.3515524e-03 4.2422250e-04 ... 1.7264845e-03
  9.8080242e-01 2.6967137e-03]
 [3.4278244e-04 5.3932029e-04 3.7075875e-05 ... 2.3194832e-04
  9.9296933e-01 2.2934898e-04]
 [2.9761362e-05 1.2512472e-04 1.9235304e-06 ... 1.6823260e-04
  9.9955231e-01 1.5397425e-04]
 ...
 [1.3817384e-04 1.7719992e-03 1.8664368e-04 ... 7.8195939e-04
  9.8204184e-01 4.8497293e-04]
 [2.4102956e-05 1.4645935e-04 1.3166890e-05 ... 6.0666036e-05
  9.9466765e-01 2.6414107e-05]
 [7.1596826e-04 8.3796342e-04 9.3072944e-05 ... 8.9887029e-04
  9.9639565e-01 1.9886281e-04]]
INFO:root:Training iteration 500 of 5000


iter 499	train disc cost	0.5539100170135498	time	0.0579839015007019


INFO:root:Saving fake samples to png: [[2.2377259e-04 4.2942923e-04 6.8405127e-05 ... 2.8633248e-04
  9.0130997e-01 5.0352729e-04]
 [4.2979889e-05 5.4514261e-05 5.5846840e-06 ... 3.2151991e-05
  9.3734282e-01 4.2092870e-05]
 [2.6172770e-06 8.5814554e-06 2.1130043e-07 ... 1.6792279e-05
  9.9436259e-01 2.0107382e-05]
 ...
 [1.6966174e-05 1.8598726e-04 2.6473066e-05 ... 1.0691948e-04
  8.7173146e-01 8.5582840e-05]
 [2.0841603e-06 8.9478499e-06 1.4061025e-06 ... 5.4724956e-06
  9.2484093e-01 3.4443576e-06]
 [9.4110881e-05 8.6060136e-05 1.3061001e-05 ... 1.2831127e-04
  9.7276783e-01 3.3661960e-05]]
INFO:root:Training iteration 600 of 5000


iter 599	train disc cost	0.9322988986968994	time	0.0583681869506836


INFO:root:Saving fake samples to png: [[9.05021661e-05 1.14033086e-04 1.97581194e-05 ... 5.67859352e-05
  4.10111159e-01 1.10523033e-04]
 [1.92617790e-05 1.45154472e-05 1.68241843e-06 ... 5.96498376e-06
  3.91738147e-01 8.89235162e-06]
 [9.82181746e-07 1.79681479e-06 5.40046514e-08 ... 2.73343471e-06
  8.14376712e-01 3.67411894e-06]
 ...
 [6.80666108e-06 4.30318141e-05 7.11369739e-06 ... 1.99910355e-05
  2.64688492e-01 1.75248224e-05]
 [7.89668434e-07 1.72002251e-06 3.19582767e-07 ... 7.19404682e-07
  2.15399504e-01 5.56447560e-07]
 [4.07135194e-05 2.31612230e-05 4.10607845e-06 ... 2.69539796e-05
  6.53559327e-01 8.39727909e-06]]
INFO:root:Training iteration 700 of 5000


iter 699	train disc cost	0.8514277935028076	time	0.05479910373687744


INFO:root:Saving fake samples to png: [[6.1023573e-04 2.3872504e-05 4.4222461e-06 ... 1.4140703e-05
  6.6406798e-01 4.1655690e-05]
 [2.1891334e-04 2.6005075e-06 3.3809241e-07 ... 1.4139015e-06
  6.6053426e-01 2.9342725e-06]
 [1.6265125e-05 2.4369265e-07 8.0769267e-09 ... 5.2616059e-07
  9.4519687e-01 1.0591505e-06]
 ...
 [6.2512692e-05 7.5677517e-06 1.3612487e-06 ... 4.4673179e-06
  5.1569402e-01 5.6032068e-06]
 [1.2823561e-05 2.1506560e-07 4.0253894e-08 ... 1.2524416e-07
  5.1583248e-01 1.3704914e-07]
 [3.9835737e-04 4.5709062e-06 9.1968928e-07 ... 6.4541000e-06
  8.4142810e-01 2.9111357e-06]]
INFO:root:Training iteration 800 of 5000


iter 799	train disc cost	0.6937568187713623	time	0.06028375387191773


INFO:root:Saving fake samples to png: [[2.3627181e-03 3.1742538e-06 7.6379933e-07 ... 3.1309962e-06
  9.4326848e-01 1.5133343e-04]
 [1.1082107e-03 2.3845422e-07 4.2214861e-08 ... 2.4967036e-07
  9.6137542e-01 1.3521230e-05]
 [1.3000691e-04 1.8224666e-08 9.6049646e-10 ... 8.0169336e-08
  9.9647909e-01 6.7686119e-06]
 ...
 [2.9030087e-04 6.9821914e-07 1.7832353e-07 ... 6.7639394e-07
  9.2758864e-01 2.2505363e-05]
 [9.0445748e-05 1.2250361e-08 3.1458827e-09 ... 1.4307652e-08
  9.5737547e-01 7.8009344e-07]
 [2.0874587e-03 4.3515007e-07 1.2463101e-07 ... 1.0778024e-06
  9.8285931e-01 1.2184586e-05]]
INFO:root:Training iteration 900 of 5000


iter 899	train disc cost	0.734652578830719	time	0.053738250732421874


INFO:root:Saving fake samples to png: [[7.4864780e-03 1.0545816e-06 1.3343598e-06 ... 1.1667723e-06
  9.8156530e-01 9.0662745e-04]
 [4.3388666e-03 5.8427364e-08 8.0350127e-08 ... 7.2317356e-08
  9.9053639e-01 1.0335757e-04]
 [7.6700031e-04 4.7490949e-09 2.5306193e-09 ... 2.6647442e-08
  9.9920160e-01 8.3323517e-05]
 ...
 [1.1247970e-03 1.6925456e-07 2.9569318e-07 ... 2.0645371e-07
  9.8205274e-01 1.5931987e-04]
 [4.9208879e-04 2.0524054e-09 6.2991292e-09 ... 3.0169816e-09
  9.9212402e-01 8.5372958e-06]
 [8.4529491e-03 1.1964075e-07 2.3029334e-07 ... 3.6624411e-07
  9.9530220e-01 9.6455697e-05]]
INFO:root:Training iteration 1000 of 5000


iter 999	train disc cost	1.1702677011489868	time	0.06251404523849487


INFO:root:Saving fake samples to png: [[1.2255015e-03 1.9043546e-07 4.7027706e-06 ... 1.6360190e-07
  9.9582052e-01 3.4274859e-03]
 [4.7205869e-04 7.2862973e-09 3.4398204e-07 ... 6.3604362e-09
  9.9855453e-01 4.6736191e-04]
 [5.9035403e-05 4.8356430e-10 1.3620543e-08 ... 2.0994224e-09
  9.9990714e-01 5.2233064e-04]
 ...
 [1.3568539e-04 2.8533130e-08 1.5674927e-06 ... 2.5942272e-08
  9.9698931e-01 8.3588238e-04]
 [3.4370405e-05 2.0866385e-10 4.5470749e-08 ... 2.0927089e-10
  9.9912769e-01 5.6497232e-05]
 [1.0057163e-03 1.7571610e-08 1.0394683e-06 ... 4.3607521e-08
  9.9924999e-01 4.7405058e-04]]
INFO:root:Training iteration 1100 of 5000


iter 1099	train disc cost	1.0472698211669922	time	0.05194474458694458


INFO:root:Saving fake samples to png: [[2.61594047e-04 2.94392617e-08 1.69011764e-05 ... 1.98443626e-08
  9.98884261e-01 4.39943373e-03]
 [8.47373158e-05 1.04216369e-09 1.91065192e-06 ... 6.40235143e-10
  9.99688864e-01 7.18075957e-04]
 [6.17873684e-06 4.27835892e-11 8.20664283e-08 ... 1.26946634e-10
  9.99984860e-01 7.18196738e-04]
 ...
 [2.35496318e-05 4.57534721e-09 9.04073659e-06 ... 2.85260948e-09
  9.99333203e-01 1.23822223e-03]
 [3.73833609e-06 1.82829550e-11 3.34514482e-07 ... 1.34743995e-11
  9.99873161e-01 8.82625900e-05]
 [1.85067373e-04 2.66564770e-09 5.45207013e-06 ... 4.65032413e-09
  9.99833226e-01 6.21451763e-04]]
INFO:root:Training iteration 1200 of 5000


iter 1199	train disc cost	1.0203845500946045	time	0.06602458477020264


INFO:root:Saving fake samples to png: [[4.40194017e-05 4.34868141e-09 5.34498722e-05 ... 2.18427409e-09
  9.99845624e-01 4.66946396e-04]
 [9.52843857e-06 1.02194544e-10 7.20574417e-06 ... 4.54830826e-11
  9.99970675e-01 4.94093547e-05]
 [5.65193034e-07 4.75819991e-12 4.34980393e-07 ... 1.16741842e-11
  9.99998808e-01 4.03859522e-05]
 ...
 [3.16789396e-06 6.84473533e-10 3.66850982e-05 ... 3.53904711e-10
  9.99916911e-01 1.06972911e-04]
 [3.09541747e-07 1.48652629e-12 1.88165802e-06 ... 7.28991086e-13
  9.99991417e-01 3.81056680e-06]
 [2.60181514e-05 4.04117878e-10 2.40497775e-05 ... 5.39726708e-10
  9.99980688e-01 5.38610475e-05]]
INFO:root:Training iteration 1300 of 5000


iter 1299	train disc cost	0.9409299492835999	time	0.05357544183731079


INFO:root:Saving fake samples to png: [[6.9299294e-06 1.2816902e-09 3.0302801e-04 ... 2.7306826e-10
  9.9997711e-01 6.6583758e-05]
 [1.0276914e-06 2.4640349e-11 5.6484248e-05 ... 4.0495701e-12
  9.9999690e-01 4.7276289e-06]
 [4.8224582e-08 1.6616296e-12 4.5607912e-06 ... 1.7021440e-12
  9.9999988e-01 4.1656353e-06]
 ...
 [4.0775430e-07 2.9428734e-10 2.6347031e-04 ... 7.4794941e-11
  9.9998701e-01 1.5539898e-05]
 [2.3739497e-08 3.6924798e-13 2.4035657e-05 ... 5.9926951e-14
  9.9999928e-01 2.8293599e-07]
 [3.9503975e-06 1.5212748e-10 1.8656735e-04 ... 8.6783677e-11
  9.9999726e-01 7.2994767e-06]]
INFO:root:Training iteration 1400 of 5000


iter 1399	train disc cost	0.9818918108940125	time	0.06242316722869873


INFO:root:Saving fake samples to png: [[1.4880902e-06 2.5753244e-09 3.3166646e-03 ... 8.2856805e-11
  9.9999440e-01 1.3086671e-05]
 [1.4330939e-07 4.7131483e-11 9.1251469e-04 ... 8.0439328e-13
  9.9999952e-01 6.1988112e-07]
 [5.8343157e-09 6.1293865e-12 1.0094966e-04 ... 7.6693551e-13
  1.0000000e+00 7.1116978e-07]
 ...
 [7.2819802e-08 9.8097552e-10 3.3688436e-03 ... 4.3124740e-11
  9.9999654e-01 3.4884897e-06]
 [2.8862350e-09 1.2957059e-12 6.7925866e-04 ... 1.5976063e-14
  9.9999988e-01 3.6284675e-08]
 [8.5294147e-07 4.3771053e-10 2.6517629e-03 ... 3.4975540e-11
  9.9999940e-01 1.4674877e-06]]
INFO:root:Training iteration 1500 of 5000


iter 1499	train disc cost	1.0114595890045166	time	0.05101366519927979


INFO:root:Saving fake samples to png: [[5.2272657e-07 1.6559095e-08 1.2018625e-01 ... 4.1105671e-11
  9.9999809e-01 4.0892787e-06]
 [3.0922362e-08 3.3964648e-10 6.7468688e-02 ... 2.5124539e-13
  9.9999988e-01 1.2268183e-07]
 [1.4642527e-09 8.7968924e-11 1.0946142e-02 ... 4.6793564e-13
  1.0000000e+00 1.8222012e-07]
 ...
 [2.7521232e-08 1.0977403e-08 1.5287019e-01 ... 4.0304312e-11
  9.9999857e-01 1.3940096e-06]
 [7.2216250e-10 2.1785886e-11 1.0758948e-01 ... 8.5079962e-15
  1.0000000e+00 8.4202636e-09]
 [3.1070229e-07 4.1797334e-09 1.2198162e-01 ... 2.1922188e-11
  9.9999976e-01 4.8495679e-07]]
INFO:root:Training iteration 1600 of 5000


iter 1599	train disc cost	1.064895749092102	time	0.06285812616348267


INFO:root:Saving fake samples to png: [[1.0080490e-07 4.5632611e-08 1.2369931e-01 ... 7.0009411e-12
  9.9999869e-01 6.5269512e-07]
 [4.3363566e-09 1.2678554e-09 7.0519187e-02 ... 3.4312349e-14
  9.9999988e-01 1.4309261e-08]
 [1.9915933e-10 4.2303158e-10 1.3393725e-02 ... 8.4079811e-14
  1.0000000e+00 2.3375282e-08]
 ...
 [5.5992282e-09 4.6022887e-08 1.9191511e-01 ... 1.1511709e-11
  9.9999857e-01 2.7028469e-07]
 [9.4506757e-11 1.2653688e-10 1.3505647e-01 ... 1.4516760e-15
  1.0000000e+00 9.5584718e-10]
 [6.7687019e-08 1.7155759e-08 1.3753483e-01 ... 5.2420225e-12
  9.9999976e-01 8.7121812e-08]]
INFO:root:Training iteration 1700 of 5000


iter 1699	train disc cost	1.0741982460021973	time	0.05128645181655884


INFO:root:Saving fake samples to png: [[1.4675191e-08 1.5049824e-07 6.0060401e-03 ... 1.2484329e-12
  9.9999416e-01 6.4334003e-08]
 [4.9017518e-10 5.5455973e-09 1.7438303e-03 ... 4.9775345e-15
  9.9999952e-01 1.0485280e-09]
 [1.8183215e-11 2.2342395e-09 2.9615525e-04 ... 1.4819019e-14
  1.0000000e+00 2.0877102e-09]
 ...
 [8.7896351e-10 2.1308608e-07 1.0620576e-02 ... 3.4885911e-12
  9.9999130e-01 3.7269761e-08]
 [7.7728865e-12 7.1944445e-10 2.3940576e-03 ... 2.2285794e-16
  9.9999988e-01 6.4371106e-11]
 [9.1373211e-09 6.0370652e-08 6.3533187e-03 ... 9.3418817e-13
  9.9999917e-01 8.3836298e-09]]
INFO:root:Training iteration 1800 of 5000


iter 1799	train disc cost	1.0372239351272583	time	0.06231791734695435


INFO:root:Saving fake samples to png: [[5.0453575e-09 7.6909203e-07 7.4757828e-04 ... 5.9795219e-13
  9.9995351e-01 1.5027645e-08]
 [1.3487700e-10 3.9951836e-08 1.4156895e-04 ... 2.1408110e-15
  9.9999535e-01 1.9495999e-10]
 [4.6165047e-12 1.7859220e-08 2.3334684e-05 ... 7.2331870e-15
  9.9999964e-01 4.3722242e-10]
 ...
 [2.9042249e-10 1.3257559e-06 1.4008965e-03 ... 2.1819599e-12
  9.9993587e-01 1.0580672e-08]
 [1.8175750e-12 6.6875065e-09 1.5397058e-04 ... 9.6824230e-17
  9.9999785e-01 1.1480988e-11]
 [2.9032075e-09 3.3658839e-07 7.3611143e-04 ... 4.3795290e-13
  9.9999356e-01 1.8930630e-09]]
INFO:root:Training iteration 1900 of 5000


iter 1899	train disc cost	1.0636422634124756	time	0.05390766382217407


INFO:root:Saving fake samples to png: [[1.8109477e-09 3.6745080e-06 8.5575906e-05 ... 1.4429983e-13
  9.9969208e-01 1.7456686e-09]
 [4.4070515e-11 2.6896890e-07 1.1548898e-05 ... 4.1619626e-16
  9.9995685e-01 1.7919518e-11]
 [1.4258939e-12 1.4100191e-07 1.9222614e-06 ... 1.8912706e-15
  9.9999726e-01 5.3561610e-11]
 ...
 [1.2389030e-10 8.2838314e-06 1.9203477e-04 ... 9.6019286e-13
  9.9947268e-01 1.8863697e-09]
 [5.8092420e-13 6.2427013e-08 1.0719476e-05 ... 2.1789226e-17
  9.9997401e-01 1.1060755e-12]
 [1.2182060e-09 1.9427478e-06 8.7721142e-05 ... 1.3317785e-13
  9.9995315e-01 2.8363101e-10]]
INFO:root:Training iteration 2000 of 5000


iter 1999	train disc cost	1.0680841207504272	time	0.060894136428833005


INFO:root:Saving fake samples to png: [[1.29451472e-09 2.53703874e-05 1.28047286e-05 ... 6.23994468e-14
  9.97326732e-01 4.43664050e-10]
 [3.02537440e-11 2.57350234e-06 1.21513403e-06 ... 1.41046206e-16
  9.99481976e-01 3.61538295e-12]
 [1.00639440e-12 1.69934833e-06 2.23718345e-07 ... 9.96108840e-16
  9.99965787e-01 1.38800004e-11]
 ...
 [9.85259790e-11 7.11352404e-05 3.52961506e-05 ... 7.02333916e-13
  9.94842827e-01 6.34842123e-10]
 [4.51183280e-13 8.60197758e-07 1.08801714e-06 ... 1.08149192e-17
  9.99606311e-01 2.74129786e-13]
 [9.75043490e-10 1.52010844e-05 1.37756733e-05 ... 6.56841931e-14
  9.99594629e-01 8.24326163e-11]]
INFO:root:Training iteration 2100 of 5000


iter 2099	train disc cost	1.0823755264282227	time	0.06086008787155151


INFO:root:Saving fake samples to png: [[1.8950899e-09 2.6972874e-04 3.4250252e-06 ... 5.0465474e-14
  9.5376647e-01 1.9801243e-10]
 [5.1984445e-11 4.2809519e-05 2.6794942e-07 ... 1.1136030e-16
  9.8468089e-01 1.5664264e-12]
 [1.3399352e-12 2.9455850e-05 4.5212250e-08 ... 7.2664246e-16
  9.9911672e-01 5.4573325e-12]
 ...
 [1.2777157e-10 7.9444650e-04 9.8705732e-06 ... 6.9077301e-13
  9.1644263e-01 2.8882824e-10]
 [7.9036799e-13 1.8885376e-05 2.1961399e-07 ... 9.2987475e-18
  9.8525244e-01 1.2052632e-13]
 [1.3850526e-09 1.6383515e-04 3.5611870e-06 ... 4.7379811e-14
  9.9343044e-01 3.7679911e-11]]
INFO:root:Training iteration 2200 of 5000


iter 2199	train disc cost	1.0917624235153198	time	0.05836421012878418


INFO:root:Saving fake samples to png: [[4.12679313e-09 1.13441106e-02 3.92209877e-05 ... 6.33626317e-14
  9.47368085e-01 1.27873490e-10]
 [1.20895113e-10 3.67422099e-03 4.73347973e-06 ... 1.24124804e-16
  9.83947873e-01 8.39345303e-13]
 [2.74228773e-12 3.08363955e-03 8.28595830e-07 ... 7.90908174e-16
  9.99128044e-01 2.47734645e-12]
 ...
 [2.76103751e-10 3.37207429e-02 1.04341205e-04 ... 1.28972917e-12
  9.00686562e-01 1.92265343e-10]
 [2.46732127e-12 2.61814287e-03 5.74697287e-06 ... 1.59556936e-17
  9.82918978e-01 7.77976113e-14]
 [3.00871794e-09 7.69911055e-03 4.62896860e-05 ... 5.86939216e-14
  9.93070543e-01 2.33904111e-11]]
INFO:root:Training iteration 2300 of 5000


iter 2299	train disc cost	1.105058193206787	time	0.059158999919891354


INFO:root:Saving fake samples to png: [[3.2723797e-09 5.5686855e-01 3.5443532e-04 ... 4.9747465e-14
  9.7045970e-01 6.3462388e-11]
 [1.0655554e-10 5.0958729e-01 6.8238136e-05 ... 1.0116329e-16
  9.9265999e-01 3.7227824e-13]
 [2.2993137e-12 5.4182810e-01 1.1694040e-05 ... 5.8967771e-16
  9.9957377e-01 8.9446907e-13]
 ...
 [2.1030644e-10 7.5964296e-01 7.1923272e-04 ... 8.5822441e-13
  9.4704688e-01 7.9702217e-11]
 [2.2850654e-12 5.6051290e-01 9.6060088e-05 ... 1.3929976e-17
  9.9223047e-01 3.0923980e-14]
 [2.7946989e-09 4.8110464e-01 4.4436150e-04 ... 4.4804519e-14
  9.9632746e-01 1.0422561e-11]]
INFO:root:Training iteration 2400 of 5000


iter 2399	train disc cost	1.1755907535552979	time	0.05524977922439575


INFO:root:Saving fake samples to png: [[4.4613020e-09 2.3948679e-02 2.7799914e-03 ... 3.4946411e-14
  9.8327231e-01 6.2284553e-11]
 [1.4189770e-10 9.2012724e-03 8.1639999e-04 ... 6.5279804e-17
  9.9609792e-01 3.8492435e-13]
 [3.0088970e-12 7.9959035e-03 1.3849529e-04 ... 4.2341369e-16
  9.9979812e-01 1.0809955e-12]
 ...
 [2.7160549e-10 6.7061283e-02 5.4287938e-03 ... 7.4993142e-13
  9.6635157e-01 9.4733429e-11]
 [2.9257443e-12 7.1686502e-03 1.3914825e-03 ... 8.9156099e-18
  9.9608225e-01 3.4982959e-14]
 [3.1638021e-09 1.6077323e-02 3.7260265e-03 ... 2.8341953e-14
  9.9805641e-01 1.0271235e-11]]
INFO:root:Training iteration 2500 of 5000


iter 2499	train disc cost	1.0707577466964722	time	0.06035326719284058


INFO:root:Saving fake samples to png: [[2.8801967e-09 1.0827215e-03 5.8675359e-04 ... 7.9219798e-15
  9.8348755e-01 1.6034363e-11]
 [9.9090416e-11 2.4931569e-04 1.3902945e-04 ... 1.5072184e-17
  9.9566686e-01 1.1370641e-13]
 [2.3262401e-12 1.6860403e-04 2.1980346e-05 ... 1.4401806e-16
  9.9980074e-01 4.2777259e-13]
 ...
 [2.0868891e-10 3.2501500e-03 1.3387442e-03 ... 2.9991322e-13
  9.6570075e-01 4.4542318e-11]
 [2.2004284e-12 1.3763535e-04 2.1842982e-04 ... 2.6528282e-18
  9.9560356e-01 1.2236055e-14]
 [2.3245490e-09 7.2795327e-04 7.9992425e-04 ... 8.4898087e-15
  9.9801159e-01 3.7007385e-12]]
INFO:root:Training iteration 2600 of 5000


iter 2599	train disc cost	1.0937011241912842	time	0.0536508584022522


INFO:root:Saving fake samples to png: [[5.5084683e-09 1.0532325e-04 8.6261345e-05 ... 3.9975479e-15
  9.9474734e-01 1.0702888e-11]
 [2.3544938e-10 1.5699250e-05 1.4700449e-05 ... 7.0383144e-18
  9.9889696e-01 7.3024452e-14]
 [6.2785237e-12 1.1016501e-05 2.3560744e-06 ... 8.7977388e-17
  9.9994516e-01 3.4225108e-13]
 ...
 [3.7510844e-10 3.7604073e-04 2.1863778e-04 ... 1.7418568e-13
  9.8758614e-01 3.1778788e-11]
 [5.8314473e-12 7.5806024e-06 2.0120213e-05 ... 1.4126844e-18
  9.9888128e-01 8.5306153e-15]
 [4.9660849e-09 6.7533489e-05 1.1420382e-04 ... 4.8329201e-15
  9.9938369e-01 2.7067226e-12]]
INFO:root:Training iteration 2700 of 5000


iter 2699	train disc cost	1.1049593687057495	time	0.062070698738098146


INFO:root:Saving fake samples to png: [[2.1969438e-08 1.4921780e-05 1.2628639e-03 ... 4.6393778e-15
  9.9926120e-01 1.4301681e-11]
 [1.4297741e-09 1.5286184e-06 3.3968917e-04 ... 9.4982585e-18
  9.9989367e-01 1.0864043e-13]
 [4.0387881e-11 1.0242062e-06 4.9291186e-05 ... 9.4584920e-17
  9.9999428e-01 4.7126669e-13]
 ...
 [1.3536029e-09 5.3562078e-05 2.3390441e-03 ... 1.2814847e-13
  9.9811232e-01 3.3009619e-11]
 [3.8438329e-11 5.9683470e-07 4.8279745e-04 ... 1.2515834e-18
  9.9989903e-01 1.0670970e-14]
 [2.4494005e-08 8.8437573e-06 1.6325557e-03 ... 5.5319734e-15
  9.9991870e-01 3.3969145e-12]]
INFO:root:Training iteration 2800 of 5000


iter 2799	train disc cost	1.1046278476715088	time	0.05170374631881714


INFO:root:Saving fake samples to png: [[1.60223024e-07 1.98256157e-06 2.30568709e-04 ... 3.59068574e-15
  9.99887109e-01 1.37783162e-11]
 [1.30767308e-08 1.45565494e-07 4.71242784e-05 ... 6.67208556e-18
  9.99988317e-01 1.06265758e-13]
 [3.20657612e-10 1.00728009e-07 6.97269525e-06 ... 6.43224313e-17
  9.99999404e-01 3.71250068e-13]
 ...
 [6.77727696e-09 8.74222587e-06 4.77225432e-04 ... 1.02136324e-13
  9.99661207e-01 2.66796914e-11]
 [3.91648658e-10 5.72729171e-08 6.60912774e-05 ... 1.07721746e-18
  9.99989629e-01 1.00567756e-14]
 [1.39780198e-07 1.00830425e-06 2.85823538e-04 ... 2.97722594e-15
  9.99989152e-01 2.44302668e-12]]
INFO:root:Training iteration 2900 of 5000


iter 2899	train disc cost	1.097344994544983	time	0.06615290403366089


INFO:root:Saving fake samples to png: [[8.73699832e-07 2.30377026e-07 1.37893239e-03 ... 1.07540023e-15
  9.99988675e-01 4.87373206e-12]
 [1.16110172e-07 1.34760381e-08 4.53298679e-04 ... 2.37358443e-18
  9.99999166e-01 4.12730254e-14]
 [3.09801407e-09 9.91998128e-09 6.60992155e-05 ... 2.82017635e-17
  1.00000000e+00 1.74177716e-13]
 ...
 [4.04401312e-08 1.51768620e-06 2.77202623e-03 ... 5.90560790e-14
  9.99951005e-01 1.35742285e-11]
 [3.97750410e-09 4.72430406e-09 7.26734346e-04 ... 4.12429358e-19
  9.99999404e-01 3.97358699e-15]
 [9.47659714e-07 1.29566089e-07 2.11493741e-03 ... 1.27629495e-15
  9.99998927e-01 1.14870277e-12]]
INFO:root:Training iteration 3000 of 5000


iter 2999	train disc cost	1.0922460556030273	time	0.05458176851272583


INFO:root:Saving fake samples to png: [[7.4203749e-06 3.6761644e-08 3.4780224e-04 ... 6.8407201e-16
  9.9999869e-01 4.2261823e-12]
 [1.4013352e-06 1.5027637e-09 9.1234884e-05 ... 1.2946917e-18
  9.9999988e-01 3.5554198e-14]
 [3.5693393e-08 9.6417851e-10 1.1892984e-05 ... 1.1458005e-17
  1.0000000e+00 1.2176089e-13]
 ...
 [2.7786308e-07 2.3105956e-07 6.4309052e-04 ... 2.6656103e-14
  9.9999309e-01 8.1852884e-12]
 [4.9278164e-08 4.0628192e-10 1.2498758e-04 ... 1.5986812e-19
  1.0000000e+00 2.6654615e-15]
 [7.7512132e-06 1.5936363e-08 4.8432179e-04 ... 5.0952981e-16
  9.9999988e-01 7.9014941e-13]]
INFO:root:Training iteration 3100 of 5000


iter 3099	train disc cost	1.0892114639282227	time	0.0647588300704956


INFO:root:Saving fake samples to png: [[7.10830936e-05 7.37775663e-09 3.92410468e-04 ... 8.13391287e-16
  9.99999762e-01 4.58171478e-12]
 [1.84909532e-05 2.03659936e-10 1.03573635e-04 ... 1.24666117e-18
  1.00000000e+00 3.15763312e-14]
 [4.93733751e-07 1.43542955e-10 1.20972854e-05 ... 1.32031343e-17
  1.00000000e+00 1.27060295e-13]
 ...
 [2.40429722e-06 5.26754036e-08 5.83838904e-04 ... 3.37885034e-14
  9.99998569e-01 8.94752761e-12]
 [7.72519797e-07 5.03188810e-11 1.26603089e-04 ... 1.72211016e-19
  1.00000000e+00 2.43788851e-15]
 [7.51140687e-05 2.89306401e-09 5.23825409e-04 ... 5.71888482e-16
  1.00000000e+00 7.69637609e-13]]
INFO:root:Training iteration 3200 of 5000


iter 3199	train disc cost	1.079187035560608	time	0.05213333368301391


INFO:root:Saving fake samples to png: [[1.96246838e-04 6.68291689e-09 4.45720332e-04 ... 3.68439824e-16
  1.00000000e+00 2.35296505e-12]
 [6.57709388e-05 1.95758146e-10 1.30077839e-04 ... 5.55405821e-19
  1.00000000e+00 1.57346772e-14]
 [1.88004003e-06 1.20843946e-10 1.30800345e-05 ... 5.01603027e-18
  1.00000000e+00 6.28112877e-14]
 ...
 [7.05260572e-06 5.28416457e-08 5.52275975e-04 ... 1.90797102e-14
  9.99999642e-01 5.12105029e-12]
 [3.30640410e-06 5.07253406e-11 1.56662209e-04 ... 7.66596289e-20
  1.00000000e+00 1.25951195e-15]
 [2.41881586e-04 2.64992250e-09 6.44819054e-04 ... 2.75547891e-16
  1.00000000e+00 4.29559139e-13]]
INFO:root:Training iteration 3300 of 5000


iter 3299	train disc cost	1.0780982971191406	time	0.06305267572402955


INFO:root:Saving fake samples to png: [[2.0746294e-05 5.0644491e-08 3.7154727e-04 ... 2.1330901e-16
  1.0000000e+00 1.7803850e-12]
 [4.4803646e-06 2.1356827e-09 1.1190698e-04 ... 2.8747763e-19
  1.0000000e+00 1.0509861e-14]
 [1.5085993e-07 1.4685936e-09 1.0173073e-05 ... 3.1221490e-18
  1.0000000e+00 5.2903005e-14]
 ...
 [9.4718439e-07 4.1069097e-07 3.9097568e-04 ... 1.4143534e-14
  9.9999988e-01 4.9409830e-12]
 [1.8812118e-07 6.2667577e-10 1.1909205e-04 ... 3.4873925e-20
  1.0000000e+00 8.0671984e-16]
 [2.5136063e-05 2.3821956e-08 5.6030345e-04 ... 1.8335152e-16
  1.0000000e+00 3.3822435e-13]]
INFO:root:Training iteration 3400 of 5000


iter 3399	train disc cost	1.0858652591705322	time	0.052308313846588135


INFO:root:Saving fake samples to png: [[2.4363067e-06 4.8817475e-07 7.4281084e-04 ... 1.0335510e-16
  1.0000000e+00 9.4783220e-13]
 [3.8791919e-07 3.2238486e-08 2.8486128e-04 ... 1.3712377e-19
  1.0000000e+00 5.5583297e-15]
 [1.2940538e-08 2.2359117e-08 2.1553820e-05 ... 1.7231689e-18
  1.0000000e+00 3.3026638e-14]
 ...
 [1.1497776e-07 3.1739605e-06 5.2940228e-04 ... 5.8437756e-15
  1.0000000e+00 2.3198596e-12]
 [1.3113422e-08 1.0646952e-08 2.8546949e-04 ... 1.4132652e-20
  1.0000000e+00 3.8493185e-16]
 [2.6705986e-06 2.3846900e-07 1.1614868e-03 ... 8.7540842e-17
  1.0000000e+00 1.8593285e-13]]
INFO:root:Training iteration 3500 of 5000


iter 3499	train disc cost	1.079869031906128	time	0.062706139087677


INFO:root:Saving fake samples to png: [[3.86937870e-07 7.06480387e-06 1.16048928e-03 ... 8.99946831e-17
  1.00000000e+00 8.29550784e-13]
 [4.88627023e-08 8.11509324e-07 5.14784886e-04 ... 1.43060706e-19
  1.00000000e+00 5.47858920e-15]
 [1.66764569e-09 5.17528747e-07 3.45098597e-05 ... 1.49095428e-18
  1.00000000e+00 2.77576915e-14]
 ...
 [2.19725376e-08 3.80338752e-05 6.86565239e-04 ... 4.72638964e-15
  1.00000000e+00 1.83524376e-12]
 [1.35256806e-09 3.12582699e-07 4.82237519e-04 ... 1.25746365e-20
  1.00000000e+00 3.23517537e-16]
 [4.27193243e-07 3.83313863e-06 1.88224693e-03 ... 7.97068525e-17
  1.00000000e+00 1.61392831e-13]]
INFO:root:Training iteration 3600 of 5000


iter 3599	train disc cost	1.0710033178329468	time	0.05534315347671509


INFO:root:Saving fake samples to png: [[1.67426504e-06 1.24193160e-04 4.85214987e-04 ... 1.27358048e-16
  1.00000000e+00 1.01744784e-12]
 [2.77634228e-07 2.38214270e-05 1.94801236e-04 ... 2.44779881e-19
  1.00000000e+00 8.02677474e-15]
 [8.46961701e-09 1.53703259e-05 1.16162455e-05 ... 2.59363039e-18
  1.00000000e+00 4.03209367e-14]
 ...
 [7.56762830e-08 6.13572483e-04 2.36568041e-04 ... 7.04823908e-15
  1.00000000e+00 2.14188823e-12]
 [8.23081159e-09 1.24527078e-05 1.57390939e-04 ... 2.75324579e-20
  1.00000000e+00 5.21891674e-16]
 [1.84304236e-06 7.44188510e-05 7.49450701e-04 ... 1.24350869e-16
  1.00000000e+00 2.12061908e-13]]
INFO:root:Training iteration 3700 of 5000


iter 3699	train disc cost	1.0779021978378296	time	0.060938704013824466


INFO:root:Saving fake samples to png: [[2.8954530e-06 8.7479558e-03 1.1208075e-03 ... 1.6259480e-16
  1.0000000e+00 1.0929622e-12]
 [5.5235682e-07 3.2639289e-03 5.5247004e-04 ... 3.8651154e-19
  1.0000000e+00 9.4325225e-15]
 [1.3552828e-08 1.7910593e-03 2.8755858e-05 ... 2.1228517e-18
  1.0000000e+00 3.0243599e-14]
 ...
 [1.2416832e-07 2.9313697e-02 4.1449070e-04 ... 7.0977765e-15
  1.0000000e+00 1.6407994e-12]
 [1.6349578e-08 2.2460609e-03 4.4609694e-04 ... 3.4835238e-20
  1.0000000e+00 5.0784935e-16]
 [3.2448747e-06 4.8391023e-03 1.8067582e-03 ... 1.4734227e-16
  1.0000000e+00 2.1965107e-13]]
INFO:root:Training iteration 3800 of 5000


iter 3799	train disc cost	1.0720570087432861	time	0.06090400218963623


INFO:root:Saving fake samples to png: [[6.68482414e-07 1.12216756e-01 1.48376392e-04 ... 1.39791181e-16
  1.00000000e+00 8.40997356e-13]
 [1.04681249e-07 6.18796684e-02 5.10461869e-05 ... 2.91169385e-19
  1.00000000e+00 6.22824088e-15]
 [2.69195555e-09 3.41794752e-02 2.63011293e-06 ... 1.72199275e-18
  1.00000000e+00 2.13806583e-14]
 ...
 [3.51353258e-08 3.37465227e-01 6.38358397e-05 ... 7.06913454e-15
  1.00000000e+00 1.39026984e-12]
 [3.00056269e-09 5.59619330e-02 3.60429804e-05 ... 2.76452776e-20
  1.00000000e+00 3.38361287e-16]
 [8.75913997e-07 5.80992699e-02 2.33380953e-04 ... 1.64542185e-16
  1.00000000e+00 2.04237668e-13]]
INFO:root:Training iteration 3900 of 5000


iter 3899	train disc cost	1.1093270778656006	time	0.05781264305114746


INFO:root:Saving fake samples to png: [[3.5619240e-07 2.7788945e-03 3.1464773e-05 ... 1.3500219e-16
  1.0000000e+00 9.0451572e-13]
 [4.4782610e-08 8.0576568e-04 8.2653105e-06 ... 2.4707926e-19
  1.0000000e+00 6.6996660e-15]
 [9.7525743e-10 3.7940394e-04 4.2200415e-07 ... 9.6386332e-19
  1.0000000e+00 1.7090682e-14]
 ...
 [1.4752396e-08 1.1265782e-02 1.5419128e-05 ... 3.6758363e-15
  1.0000000e+00 9.8051753e-13]
 [9.5837926e-10 4.6811317e-04 4.9231658e-06 ... 1.4755909e-20
  1.0000000e+00 2.5603085e-16]
 [3.4284068e-07 1.3424053e-03 4.3580578e-05 ... 9.9239909e-17
  1.0000000e+00 1.6135251e-13]]
INFO:root:Training iteration 4000 of 5000


iter 3999	train disc cost	1.073258638381958	time	0.06008088827133179


INFO:root:Saving fake samples to png: [[3.6491269e-06 2.2257397e-04 6.6105771e-04 ... 1.8573656e-16
  1.0000000e+00 1.2516183e-12]
 [6.5139858e-07 4.5684807e-05 2.7850401e-04 ... 3.7413707e-19
  1.0000000e+00 9.8689587e-15]
 [1.7297836e-08 2.0126949e-05 1.7756676e-05 ... 1.2803991e-18
  1.0000000e+00 2.4958551e-14]
 ...
 [1.4389541e-07 1.0162455e-03 3.1659773e-04 ... 3.8115047e-15
  1.0000000e+00 1.1288121e-12]
 [1.6721470e-08 2.1153917e-05 2.2178212e-04 ... 2.0174321e-20
  1.0000000e+00 3.3248579e-16]
 [3.3276901e-06 9.8435434e-05 9.3363796e-04 ... 1.0107880e-16
  1.0000000e+00 1.7211795e-13]]
INFO:root:Training iteration 4100 of 5000


iter 4099	train disc cost	1.085869312286377	time	0.05515920639038086


INFO:root:Saving fake samples to png: [[4.6797988e-05 2.8014740e-05 1.4096505e-02 ... 2.0145215e-16
  1.0000000e+00 1.4891627e-12]
 [1.3118737e-05 4.4262588e-06 9.9995835e-03 ... 5.4851236e-19
  1.0000000e+00 1.3195223e-14]
 [3.6123924e-07 1.6915290e-06 6.4778182e-04 ... 1.3748630e-18
  1.0000000e+00 2.6821239e-14]
 ...
 [2.1846101e-06 1.3127305e-04 6.3717556e-03 ... 4.2067053e-15
  1.0000000e+00 1.3342735e-12]
 [4.5058934e-07 1.5218835e-06 1.0869416e-02 ... 2.1508740e-20
  1.0000000e+00 3.5153281e-16]
 [5.1060211e-05 1.3034310e-05 2.3090059e-02 ... 1.7248214e-16
  1.0000000e+00 2.5718880e-13]]
INFO:root:Training iteration 4200 of 5000


iter 4199	train disc cost	1.084356665611267	time	0.060696196556091306


INFO:root:Saving fake samples to png: [[1.7302400e-04 5.1127195e-06 5.5279122e-03 ... 5.4411591e-16
  1.0000000e+00 3.2576654e-12]
 [5.4039574e-05 5.5171557e-07 3.2969913e-03 ... 1.2683721e-18
  1.0000000e+00 2.7211828e-14]
 [1.1688950e-06 1.5827393e-07 1.5896706e-04 ... 1.9441776e-18
  1.0000000e+00 3.7514347e-14]
 ...
 [5.1956595e-06 1.8783445e-05 2.1085809e-03 ... 4.3922567e-15
  1.0000000e+00 1.3976346e-12]
 [1.8270524e-06 1.4327060e-07 2.9547599e-03 ... 3.5789433e-20
  1.0000000e+00 5.8542370e-16]
 [1.7309065e-04 1.7812566e-06 8.1387656e-03 ... 2.4814508e-16
  1.0000000e+00 3.7600473e-13]]
INFO:root:Training iteration 4300 of 5000


iter 4299	train disc cost	1.0931280851364136	time	0.053192508220672605


INFO:root:Saving fake samples to png: [[1.4191526e-05 7.2425291e-07 5.4770656e-04 ... 2.7453645e-16
  1.0000000e+00 1.9166140e-12]
 [3.0854990e-06 6.0978564e-08 2.2950888e-04 ... 6.5432814e-19
  1.0000000e+00 1.6174745e-14]
 [5.5477898e-08 1.3486119e-08 9.5748301e-06 ... 7.0587184e-19
  1.0000000e+00 1.6457154e-14]
 ...
 [4.8611901e-07 2.4950214e-06 2.2882587e-04 ... 1.8854504e-15
  1.0000000e+00 7.7345942e-13]
 [7.0794954e-08 1.0500516e-08 1.4966477e-04 ... 1.2520118e-20
  1.0000000e+00 2.4517366e-16]
 [1.1782014e-05 2.2207753e-07 6.9945020e-04 ... 1.2387882e-16
  1.0000000e+00 2.1010885e-13]]
INFO:root:Training iteration 4400 of 5000


iter 4399	train disc cost	1.0970286130905151	time	0.06268274784088135


INFO:root:Saving fake samples to png: [[1.9021487e-06 1.8336108e-07 8.4908788e-05 ... 1.8935583e-16
  1.0000000e+00 1.5261353e-12]
 [3.0803079e-07 1.4205165e-08 2.6478598e-05 ... 5.6074507e-19
  1.0000000e+00 1.4354513e-14]
 [4.2384185e-09 2.1760282e-09 8.6603302e-07 ... 3.9787514e-19
  1.0000000e+00 1.0083896e-14]
 ...
 [6.2544885e-08 5.7946869e-07 3.2730473e-05 ... 1.1522098e-15
  1.0000000e+00 5.3408639e-13]
 [4.8095781e-09 1.8154056e-09 1.2129654e-05 ... 8.6161443e-21
  1.0000000e+00 1.7038229e-16]
 [1.2590669e-06 4.7103956e-08 8.7364017e-05 ... 7.5330028e-17
  1.0000000e+00 1.3992636e-13]]
INFO:root:Training iteration 4500 of 5000


iter 4499	train disc cost	1.0680515766143799	time	0.05169339656829834


INFO:root:Saving fake samples to png: [[3.1922730e-07 1.2392811e-06 5.6588301e-04 ... 2.8711421e-16
  1.0000000e+00 1.8212990e-12]
 [4.2723634e-08 1.3906113e-07 2.5144918e-04 ... 1.0681375e-18
  1.0000000e+00 1.9295856e-14]
 [3.2632530e-10 1.8304862e-08 6.9103166e-06 ... 4.4484662e-19
  1.0000000e+00 8.1556974e-15]
 ...
 [9.7537889e-09 3.3251617e-06 1.9342349e-04 ... 1.4404341e-15
  1.0000000e+00 5.1098660e-13]
 [4.6772841e-10 2.0214232e-08 1.3347078e-04 ... 1.4423988e-20
  1.0000000e+00 1.8808161e-16]
 [1.8116057e-07 3.3929044e-07 6.2622584e-04 ... 1.1131060e-16
  1.0000000e+00 1.5330695e-13]]
INFO:root:Training iteration 4600 of 5000


iter 4599	train disc cost	1.0776020288467407	time	0.06519243955612182


INFO:root:Saving fake samples to png: [[6.7690372e-08 1.9560925e-05 1.4669601e-02 ... 3.2548948e-16
  1.0000000e+00 2.0583613e-12]
 [7.8418907e-09 3.5576502e-06 1.1198557e-02 ... 1.4325901e-18
  1.0000000e+00 2.3676570e-14]
 [4.0525854e-11 5.3662927e-07 3.3721453e-04 ... 4.1460937e-19
  1.0000000e+00 7.8932019e-15]
 ...
 [1.9532933e-09 4.9744129e-05 4.2065261e-03 ... 1.4041120e-15
  1.0000000e+00 4.7916760e-13]
 [6.6234573e-11 7.2324241e-07 9.0711610e-03 ... 1.6564143e-20
  1.0000000e+00 2.0330652e-16]
 [3.6403769e-08 6.5181830e-06 2.0048257e-02 ... 1.2644023e-16
  1.0000000e+00 1.6752456e-13]]
INFO:root:Training iteration 4700 of 5000


iter 4699	train disc cost	1.0724290609359741	time	0.05348801612854004


INFO:root:Saving fake samples to png: [[2.0162020e-08 2.9029316e-04 4.7263568e-03 ... 2.9290214e-16
  1.0000000e+00 1.8276496e-12]
 [2.0225794e-09 8.0604099e-05 3.2373138e-03 ... 1.3260215e-18
  1.0000000e+00 2.0828328e-14]
 [8.7108836e-12 1.6322369e-05 8.5419371e-05 ... 3.5902402e-19
  1.0000000e+00 6.9992874e-15]
 ...
 [5.9245281e-10 7.5981609e-04 1.3262148e-03 ... 1.2111638e-15
  1.0000000e+00 3.9350728e-13]
 [1.4123798e-11 2.4310139e-05 2.3132097e-03 ... 1.4618139e-20
  1.0000000e+00 1.6469604e-16]
 [1.0537795e-08 1.1806457e-04 6.3218791e-03 ... 1.2265623e-16
  1.0000000e+00 1.5569089e-13]]
INFO:root:Training iteration 4800 of 5000


iter 4799	train disc cost	1.0809402465820312	time	0.06285178899765015


INFO:root:Saving fake samples to png: [[1.67643250e-08 9.29330662e-03 6.34133932e-04 ... 3.76613506e-16
  1.00000000e+00 2.26288064e-12]
 [1.33867784e-09 4.01199469e-03 2.98088853e-04 ... 1.28340153e-18
  1.00000000e+00 2.07329644e-14]
 [5.74943261e-12 1.10450143e-03 6.71073940e-06 ... 4.50196771e-19
  1.00000000e+00 8.90729429e-15]
 ...
 [3.89740962e-10 2.34718807e-02 1.63652323e-04 ... 1.15988753e-15
  1.00000000e+00 3.78865586e-13]
 [8.23254225e-12 1.93273160e-03 1.57944349e-04 ... 1.17060605e-20
  1.00000000e+00 1.49523894e-16]
 [8.23987456e-09 4.21412895e-03 7.34974106e-04 ... 1.45820785e-16
  1.00000000e+00 1.84022732e-13]]
INFO:root:Training iteration 4900 of 5000


iter 4899	train disc cost	1.077291488647461	time	0.05146798849105835


INFO:root:Saving fake samples to png: [[6.14120355e-09 9.11349989e-03 9.17583020e-05 ... 3.10891241e-16
  1.00000000e+00 1.90312826e-12]
 [4.58724586e-10 3.98062868e-03 3.28028400e-05 ... 1.13997100e-18
  1.00000000e+00 1.84569242e-14]
 [1.79954109e-12 6.40755577e-04 5.97812800e-07 ... 3.50751360e-19
  1.00000000e+00 7.51429778e-15]
 ...
 [1.55366900e-10 2.14686282e-02 2.45748379e-05 ... 9.47944641e-16
  1.00000000e+00 3.25543385e-13]
 [2.20467568e-12 1.62973860e-03 1.24526596e-05 ... 9.09480479e-21
  1.00000000e+00 1.17652665e-16]
 [2.76326229e-09 3.32878297e-03 8.98381113e-05 ... 1.08842907e-16
  1.00000000e+00 1.44017177e-13]]
DEBUG:root:Training complete.


iter 4999	train disc cost	1.0703986883163452	time	0.06276538848876953


## Evaluate results

#### Train data (Normal)

In [5]:
def model_accuracy(data, status, mean=None):
    eval = detective.detect(data).data * -1
    if mean is None:
        mean = np.median(eval)
    ground_truth = [status] * len(eval)
    prediction = [1 if x >= mean else 0 for x in eval]
    print('Accuracy: {0:.2f}%'.format(100*accuracy_score(ground_truth, prediction)))
    return mean

In [6]:
mean = model_accuracy(data_normal_train, 1)

INFO:root:Running detector on <alphai_watson.datasource.Sample object at 0x7f98f48a0ac8>
INFO:root:Detection completed in 1.0054524950683117


Accuracy: 50.00%


#### Test data (Normal)

In [7]:
_ = model_accuracy(data_normal_test, 1, mean)

INFO:root:Running detector on <alphai_watson.datasource.Sample object at 0x7f98f48a0940>
INFO:root:Detection completed in 0.4644233528524637


Accuracy: 50.18%


#### Test data (Abnormal)

In [8]:
_ = model_accuracy(data_abnormal_test, 0, mean)

INFO:root:Running detector on <alphai_watson.datasource.Sample object at 0x7f98f48a0dd8>
INFO:root:Detection completed in 5.709230713546276


Accuracy: 52.99%
