In [1]:
import os
import numpy as np
from alphai_watson.datasource.brainwaves import BrainwavesDataSource
from alphai_watson.performance import GANPerformanceAnalysis
from alphai_watson.transformer import NullTransformer

from alphai_rickandmorty_oracle.detective import RickAndMortyDetective

/opt/anaconda/envs/ai/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/opt/anaconda/envs/ai/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


Enabling weight norm
Uppercase local vars:
	BATCH_SIZE: 50
	CRITIC_ITERS: 5
	DEFAULT_FIT_EPOCHS: 1000
	DEFAULT_LEARN_RATE: 0.0001
	DEFAULT_TRAIN_ITERS: 5000
	DEFAULT_Z_DIM: 128
	DIAGNOSIS_LEARN_RATE: 0.01
	DIM: 64
	DISC_FILTER_SIZE: 5
	LAMBDA: 10
	LAMBDA_2: 2.0
	OUTPUT_DIM: 784


In [2]:
test_data_file = os.path.join('../../tests/resources', 'brainwaves_normal_sample_1.hd5')
n_sensors = 16
n_timesteps = 784 // n_sensors

train_data_source = BrainwavesDataSource(source_file=test_data_file,
                                         transformer=NullTransformer(number_of_timesteps=n_timesteps, number_of_sensors=n_sensors))

train_data = train_data_source.get_train_data('NORMAL')


detective = RickAndMortyDetective(model_configuration={
    'batch_size': 64,
    'output_dimensions': 784,
    'train_iters': 200,
    'plot_save_path' : './'
})

detective.train(train_data)

DEBUG:root:Start file parsing
DEBUG:root:end file parsing
DEBUG:root:Starting session
DEBUG:root:Start training loop...
INFO:root:Initialising Model
INFO:root:Training iteration 0 of 200
DEBUG:matplotlib.font_manager:findfont: Matching :family=sans-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to DejaVu Sans ('/opt/anaconda/envs/ai/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf') with score of 0.050000


iter 0	train disc cost	2783.41357421875	time	1.3952929973602295
iter 1	train disc cost	2996.73779296875	time	0.46152782440185547
iter 2	train disc cost	4892.0732421875	time	0.3380753993988037
iter 3	train disc cost	2903.062744140625	time	0.33823108673095703
iter 4	train disc cost	2871.438720703125	time	0.3393216133117676


INFO:root:Training iteration 10 of 200
INFO:root:Training iteration 20 of 200
INFO:root:Training iteration 30 of 200
INFO:root:Training iteration 40 of 200
INFO:root:Training iteration 50 of 200
INFO:root:Training iteration 60 of 200
INFO:root:Training iteration 70 of 200
INFO:root:Training iteration 80 of 200
INFO:root:Training iteration 90 of 200
INFO:root:Saving fake samples to png: [[0.5030857  0.544858   0.49492484 ... 0.7492131  0.89291406 0.9780945 ]
 [0.51108694 0.54185027 0.4967971  ... 0.7459993  0.91372037 0.9845627 ]
 [0.50457805 0.54760975 0.4972567  ... 0.7427397  0.9200184  0.98735166]
 ...
 [0.50364536 0.5426374  0.5022158  ... 0.7978005  0.9262187  0.9900357 ]
 [0.50240666 0.5593554  0.50057614 ... 0.78998625 0.90843993 0.9793297 ]
 [0.5083872  0.545683   0.50745004 ... 0.7465484  0.8624125  0.9712631 ]]
INFO:root:Training iteration 100 of 200


iter 99	train disc cost	898.237060546875	time	0.33785836320174367


INFO:root:Training iteration 110 of 200
INFO:root:Training iteration 120 of 200
INFO:root:Training iteration 130 of 200
INFO:root:Training iteration 140 of 200
INFO:root:Training iteration 150 of 200
INFO:root:Training iteration 160 of 200
INFO:root:Training iteration 170 of 200
INFO:root:Training iteration 180 of 200
INFO:root:Training iteration 190 of 200
INFO:root:Saving fake samples to png: [[0.5180448  0.66040677 0.51427233 ... 0.9899194  0.9998234  0.9972493 ]
 [0.52614874 0.65220255 0.5036271  ... 0.99380714 0.99986756 0.99854183]
 [0.5218376  0.66427636 0.5159245  ... 0.99389476 0.9998958  0.9988256 ]
 ...
 [0.51996326 0.65759516 0.5184879  ... 0.99703264 0.9999434  0.9991491 ]
 [0.5128085  0.6703463  0.51593167 ... 0.9931938  0.99978334 0.9977235 ]
 [0.5254082  0.65444064 0.52299637 ... 0.9916426  0.99938107 0.99630725]]
DEBUG:root:Training complete.


iter 199	train disc cost	93.08770751953125	time	0.3376935648918152


In [3]:
train_data